services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - ../projet-vente-en-ligne/:/var/www/html/projet-vente-en-ligne
    ports:
      - '8080:80'
    depends_on:
      - db
    env_file:
      - ../.env
    command: >
      sh -c "composer install --working-dir=/var/www/html/projet-vente-en-ligne && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql-db
    env_file:
      - ../.env
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/:/docker-entrypoint-initdb.d/

    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    env_file:
      - ../.env
    ports:
      - '8081:80'
    depends_on:
      - db

volumes:
  db_data:
